//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type MpaaRating string

const (
	MpaaRating_G    MpaaRating = "G"
	MpaaRating_Pg   MpaaRating = "PG"
	MpaaRating_Pg13 MpaaRating = "PG-13"
	MpaaRating_R    MpaaRating = "R"
	MpaaRating_Nc17 MpaaRating = "NC-17"
)

var MpaaRatingAllValues = []MpaaRating{
	MpaaRating_G,
	MpaaRating_Pg,
	MpaaRating_Pg13,
	MpaaRating_R,
	MpaaRating_Nc17,
}

func (e *MpaaRating) Scan(value interface{}) error { _ = "STUB: not implemented"; return nil }

func (e MpaaRating) String() string { _ = "STUB: not implemented"; return "" }
