//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var CustomerList = newCustomerListTable("dvds", "customer_list", "")

type customerListTable struct {
	postgres.Table

	// Columns
	ID      postgres.ColumnInteger
	Name    postgres.ColumnString
	Address postgres.ColumnString
	ZipCode postgres.ColumnString
	Phone   postgres.ColumnString
	City    postgres.ColumnString
	Country postgres.ColumnString
	Notes   postgres.ColumnString
	Sid     postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CustomerListTable struct {
	customerListTable

	EXCLUDED customerListTable
}

// AS creates new CustomerListTable with assigned alias
func (a CustomerListTable) AS(alias string) *CustomerListTable {
	_ = "STUB: not implemented"
	return nil
}

// Schema creates new CustomerListTable with assigned schema name
func (a CustomerListTable) FromSchema(schemaName string) *CustomerListTable {
	_ = "STUB: not implemented"
	return nil
}

// WithPrefix creates new CustomerListTable with assigned table prefix
func (a CustomerListTable) WithPrefix(prefix string) *CustomerListTable {
	_ = "STUB: not implemented"
	return nil
}

// WithSuffix creates new CustomerListTable with assigned table suffix
func (a CustomerListTable) WithSuffix(suffix string) *CustomerListTable {
	_ = "STUB: not implemented"
	return nil
}

func newCustomerListTable(schemaName, tableName, alias string) *CustomerListTable {
	_ = "STUB: not implemented"
	return nil
}

func newCustomerListTableImpl(schemaName, tableName, alias string) customerListTable {
	_ = "STUB: not implemented"
	return *new(customerListTable)
}

//Columns
