//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Category = newCategoryTable("dvds", "category", "")

type categoryTable struct {
	postgres.Table

	// Columns
	CategoryID postgres.ColumnInteger
	Name       postgres.ColumnString
	LastUpdate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type CategoryTable struct {
	categoryTable

	EXCLUDED categoryTable
}

// AS creates new CategoryTable with assigned alias
func (a CategoryTable) AS(alias string) *CategoryTable { _ = "STUB: not implemented"; return nil }

// Schema creates new CategoryTable with assigned schema name
func (a CategoryTable) FromSchema(schemaName string) *CategoryTable {
	_ = "STUB: not implemented"
	return nil
}

// WithPrefix creates new CategoryTable with assigned table prefix
func (a CategoryTable) WithPrefix(prefix string) *CategoryTable {
	_ = "STUB: not implemented"
	return nil
}

// WithSuffix creates new CategoryTable with assigned table suffix
func (a CategoryTable) WithSuffix(suffix string) *CategoryTable {
	_ = "STUB: not implemented"
	return nil
}

func newCategoryTable(schemaName, tableName, alias string) *CategoryTable {
	_ = "STUB: not implemented"
	return nil
}

func newCategoryTableImpl(schemaName, tableName, alias string) categoryTable {
	_ = "STUB: not implemented"
	return *new(categoryTable)
}

//Columns
