//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FilmCategory = newFilmCategoryTable("dvds", "film_category", "")

type filmCategoryTable struct {
	postgres.Table

	// Columns
	FilmID     postgres.ColumnInteger
	CategoryID postgres.ColumnInteger
	LastUpdate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FilmCategoryTable struct {
	filmCategoryTable

	EXCLUDED filmCategoryTable
}

// AS creates new FilmCategoryTable with assigned alias
func (a FilmCategoryTable) AS(alias string) *FilmCategoryTable {
	_ = "STUB: not implemented"
	return nil
}

// Schema creates new FilmCategoryTable with assigned schema name
func (a FilmCategoryTable) FromSchema(schemaName string) *FilmCategoryTable {
	_ = "STUB: not implemented"
	return nil
}

// WithPrefix creates new FilmCategoryTable with assigned table prefix
func (a FilmCategoryTable) WithPrefix(prefix string) *FilmCategoryTable {
	_ = "STUB: not implemented"
	return nil
}

// WithSuffix creates new FilmCategoryTable with assigned table suffix
func (a FilmCategoryTable) WithSuffix(suffix string) *FilmCategoryTable {
	_ = "STUB: not implemented"
	return nil
}

func newFilmCategoryTable(schemaName, tableName, alias string) *FilmCategoryTable {
	_ = "STUB: not implemented"
	return nil
}

func newFilmCategoryTableImpl(schemaName, tableName, alias string) filmCategoryTable {
	_ = "STUB: not implemented"
	return *new(filmCategoryTable)
}

//Columns
