//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Film = newFilmTable("dvds", "film", "")

type filmTable struct {
	postgres.Table

	// Columns
	FilmID          postgres.ColumnInteger
	Title           postgres.ColumnString
	Description     postgres.ColumnString
	ReleaseYear     postgres.ColumnInteger
	LanguageID      postgres.ColumnInteger
	RentalDuration  postgres.ColumnInteger
	RentalRate      postgres.ColumnFloat
	Length          postgres.ColumnInteger
	ReplacementCost postgres.ColumnFloat
	Rating          postgres.ColumnString
	LastUpdate      postgres.ColumnTimestamp
	SpecialFeatures postgres.ColumnStringArray
	Fulltext        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FilmTable struct {
	filmTable

	EXCLUDED filmTable
}

// AS creates new FilmTable with assigned alias
func (a FilmTable) AS(alias string) *FilmTable { _ = "STUB: not implemented"; return nil }

// Schema creates new FilmTable with assigned schema name
func (a FilmTable) FromSchema(schemaName string) *FilmTable { _ = "STUB: not implemented"; return nil }

// WithPrefix creates new FilmTable with assigned table prefix
func (a FilmTable) WithPrefix(prefix string) *FilmTable { _ = "STUB: not implemented"; return nil }

// WithSuffix creates new FilmTable with assigned table suffix
func (a FilmTable) WithSuffix(suffix string) *FilmTable { _ = "STUB: not implemented"; return nil }

func newFilmTable(schemaName, tableName, alias string) *FilmTable {
	_ = "STUB: not implemented"
	return nil
}

func newFilmTableImpl(schemaName, tableName, alias string) filmTable {
	_ = "STUB: not implemented"
	return *new(filmTable)
}

//Columns
