//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var FilmActor = newFilmActorTable("dvds", "film_actor", "")

type filmActorTable struct {
	postgres.Table

	// Columns
	ActorID    postgres.ColumnInteger
	FilmID     postgres.ColumnInteger
	LastUpdate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type FilmActorTable struct {
	filmActorTable

	EXCLUDED filmActorTable
}

// AS creates new FilmActorTable with assigned alias
func (a FilmActorTable) AS(alias string) *FilmActorTable { _ = "STUB: not implemented"; return nil }

// Schema creates new FilmActorTable with assigned schema name
func (a FilmActorTable) FromSchema(schemaName string) *FilmActorTable {
	_ = "STUB: not implemented"
	return nil
}

// WithPrefix creates new FilmActorTable with assigned table prefix
func (a FilmActorTable) WithPrefix(prefix string) *FilmActorTable {
	_ = "STUB: not implemented"
	return nil
}

// WithSuffix creates new FilmActorTable with assigned table suffix
func (a FilmActorTable) WithSuffix(suffix string) *FilmActorTable {
	_ = "STUB: not implemented"
	return nil
}

func newFilmActorTable(schemaName, tableName, alias string) *FilmActorTable {
	_ = "STUB: not implemented"
	return nil
}

func newFilmActorTableImpl(schemaName, tableName, alias string) filmActorTable {
	_ = "STUB: not implemented"
	return *new(filmActorTable)
}

//Columns
