//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Language = newLanguageTable("dvds", "language", "")

type languageTable struct {
	postgres.Table

	// Columns
	LanguageID postgres.ColumnInteger
	Name       postgres.ColumnString
	LastUpdate postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type LanguageTable struct {
	languageTable

	EXCLUDED languageTable
}

// AS creates new LanguageTable with assigned alias
func (a LanguageTable) AS(alias string) *LanguageTable { _ = "STUB: not implemented"; return nil }

// Schema creates new LanguageTable with assigned schema name
func (a LanguageTable) FromSchema(schemaName string) *LanguageTable {
	_ = "STUB: not implemented"
	return nil
}

// WithPrefix creates new LanguageTable with assigned table prefix
func (a LanguageTable) WithPrefix(prefix string) *LanguageTable {
	_ = "STUB: not implemented"
	return nil
}

// WithSuffix creates new LanguageTable with assigned table suffix
func (a LanguageTable) WithSuffix(suffix string) *LanguageTable {
	_ = "STUB: not implemented"
	return nil
}

func newLanguageTable(schemaName, tableName, alias string) *LanguageTable {
	_ = "STUB: not implemented"
	return nil
}

func newLanguageTableImpl(schemaName, tableName, alias string) languageTable {
	_ = "STUB: not implemented"
	return *new(languageTable)
}

//Columns
